// MIT License
// Sof Digital Corporation 2025
// Written By Michael Rinderle <michael@sofdigital.net>

using Microsoft.Extensions.AI;
using SofDigital.Sempai.Core.Configurations;

namespace SofDigital.Sempai.Core.Agents;

/// <summary>
///     Defines the configuration settings for an AI agent, including its connector, name, operational mode,
/// </summary>
public class AgentConfiguration
{
    /// <summary>
    ///     Gets or sets the name of the agent.
    /// </summary>
    /// <remarks>
    ///     The <c>AgentName</c> property is used to designate a unique identifier or label for an agent.
    ///     This property is essential for agent creation and configuration processes, as it provides
    ///     a reference name to associate the agent with its settings and operations.
    ///     The value of this property is utilized in the initialization of agents in various contexts,
    ///     such as Azure AI, Google Gemini, or other supported platforms. Proper assignment of this
    ///     property ensures accurate identification and management of agents within the system.
    ///     This property can accept a null or string value.
    /// </remarks>
    public string? AgentName { get; set; }

    /// <summary>
    ///     Gets or sets a value that determines whether the agent operates in an autonomous mode.
    /// </summary>
    /// <remarks>
    ///     The <c>Autonomous</c> property is used to configure the agent's operational behavior.
    ///     When set to <c>true</c>, the agent follows an autonomous plan-act-reflect loop, enabling it to
    ///     perform tasks without continuous external input. This mode is suitable for scenarios
    ///     requiring independent decision-making and execution.
    ///     By default, this property is set to <c>false</c>, requiring explicit user interaction
    ///     or guidance in its operations. Adjusting this setting impacts the agent's workflow
    ///     and level of independent activity within the system.
    /// </remarks>
    public bool Autonomous { get; set; } = false; // plan - act - reflect

    /// <summary>
    ///     Gets or sets the operational instructions for the agent.
    /// </summary>
    /// <remarks>
    ///     The <c>Instructions</c> property defines specific guidance or directives that the agent
    ///     should follow during runtime. These instructions can include task definitions, behavioral constraints,
    ///     or configuration details essential for the agent's operation within different platforms or systems.
    ///     This property is utilized in constructing agents in various contexts, such as Azure OpenAI or Anthropic,
    ///     where proper instructions ensure that the agent performs its intended functions effectively.
    ///     A null or string value can be assigned to this property.
    /// </remarks>
    public string? Instructions { get; set; }

    /// <summary>
    ///     Gets or sets the maximum number of output tokens allowed for a response.
    /// </summary>
    /// <remarks>
    ///     The <c>MaxOutputTokens</c> property defines an upper limit on the number of tokens
    ///     that can be generated as part of a single response. A token typically represents
    ///     a unit of text, such as a word or character. This property is crucial for managing
    ///     and controlling the length of responses generated by agents, ensuring that they
    ///     remain within acceptable limits for the given application context.
    ///     Configuring this property appropriately can help optimize output and resource
    ///     utilization.
    /// </remarks>
    public int MaxOutputTokens { get; set; } = 1024;

    /// <summary>
    ///     Gets or sets the temperature value used for agent configuration.
    /// </summary>
    /// <remarks>
    ///     The <c>Temperature</c> property determines the randomness of the agent's responses.
    ///     Higher values (e.g., closer to 1.0) result in more diverse and creative outputs, while lower values
    ///     (e.g., closer to 0.0) produce more focused and deterministic results. This property is
    ///     commonly utilized in Natural Language Processing (NLP) and similar tasks to strike a balance
    ///     between coherent and varied responses.
    ///     If not explicitly set, this property defaults to a value of 0.7f. A null value will also
    ///     default to 0.7f during runtime. Adjust the value as needed to fit the requirements of the
    ///     specific application or use case.
    /// </remarks>
    public float? Temperature { get; set; } = 0.7f;

    /// <summary>
    ///     Gets or sets a value indicating whether the agent operates in a threaded mode.
    /// </summary>
    /// <remarks>
    ///     The <c>Threaded</c> property determines if the agent runs within its own thread, enabling
    ///     concurrent or asynchronous operations. When set to <c>true</c>, the agent leverages a dedicated
    ///     thread for processing tasks independently, which can be essential for complex or long-running tasks.
    ///     Setting this property to <c>false</c> implies that the agent operates in a synchronous mode,
    ///     potentially sharing execution context with other operations.
    ///     This property is particularly useful for scenarios requiring parallel execution or isolation
    ///     of task workflows within the agent's lifecycle.
    /// </remarks>
    public bool Threaded { get; set; } = false;

    /// <summary>
    ///     Gets or sets the collection of tools available to the AI agent.
    /// </summary>
    /// <remarks>
    ///     The <c>Tools</c> property represents a list of <c>AITool</c> instances that the agent can utilize
    ///     during its operations. This property allows for extending the agent's functionality by enabling access
    ///     to various tools that provide specific capabilities or services.
    ///     Tools are dynamically configurable, and the availability of specific tools can influence the agent's
    ///     behavior and output depending on its configuration and operational context. Proper configuration of this
    ///     property ensures that the agent is equipped with the appropriate tools required for its intended use cases.
    ///     This property can be empty or null, in which case the agent operates without additional tools.
    /// </remarks>
    public List<AITool> Tools { get; set; } = [];

    /// <summary>
    ///     Gets or sets a value indicating whether web search functionality is enabled for the agent.
    /// </summary>
    /// <remarks>
    ///     The <c>WebSearchEnabled</c> property determines whether the agent is permitted to access
    ///     external web search capabilities during its operations. When set to <c>true</c>, the agent
    ///     can query online resources to retrieve additional information, enhancing its ability to
    ///     provide accurate or updated responses. When <c>false</c>, such functionality is disabled,
    ///     limiting the agent to its pre-existing knowledge and tools.
    ///     This property plays a critical role in controlling the scope of information accessible
    ///     by the agent, ensuring compliance with desired operational constraints.
    ///     Proper configuration of this property can impact both the performance and privacy considerations
    ///     of the agent's actions.
    /// </remarks>
    public bool WebSearchEnabled { get; set; } = false;
}

/// <summary>
///     Defines a generic configuration wrapper for an AI agent, allowing for strongly-typed parameters.
/// </summary>
/// <typeparam name="TParameters"></typeparam>
public class AgentConfiguration<TParameters> : AgentConfiguration, IConfigurationWrapper
    where TParameters : class, IAgentParameters
{
    /// <summary>
    ///     Gets or sets the strongly-typed parameters associated with the agent configuration.
    /// </summary>
    /// <typeparamref name="TParameters" />
    /// must implement the
    /// <c>IAgentParameters</c>
    /// interface, ensuring
    /// adherence to a defined structure for agent-specific parameters. This property enables precise and
    /// type-safe assignment of configuration data to an agent, allowing for specialized behavior
    /// and functionality tailored to the requirements defined in
    /// <typeparamref name="TParameters" />
    /// .
    /// </summary>
    /// <remarks>
    ///     The <c>Parameters</c> property serves as a core component of the generic <c>AgentConfiguration</c>,
    ///     allowing developers to encapsulate and manage agent-specific settings in a modular fashion. This abstraction
    ///     supports flexibility in defining unique configuration schemas for various agent types while maintaining
    ///     consistency in the broader configuration system.
    /// </remarks>
    public required TParameters Parameters { get; set; }

    object IConfigurationWrapper.ParametersObject => Parameters;
}